- name: Reset k3s cluster
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: techno_tim.k3s_ansible.reset
    - role: techno_tim.k3s_ansible.raspberrypi
      vars: {state: absent}
  post_tasks:
    - name: Reboot and wait for node to come back up
      reboot:
        reboot_timeout: 3600

- name: Revert changes to Proxmox cluster
  hosts: proxmox
  gather_facts: true
  become: true
  remote_user: "{{ proxmox_lxc_ssh_user }}"
  roles:
    - role: techno_tim.k3s_ansible.reset_proxmox_lxc
      when: proxmox_lxc_configure
