---
galaxy_info:
  role_name: argocd
  namespace: homelab
  author: tmalsdorf
  description: Deploy and configure ArgoCD on Kubernetes
  company: HomeLab
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - kubernetes
    - k3s
    - gitops
    - argocd
    - cd

dependencies: []
